import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, relative, resolve, sep } from 'node:path';
import type { Env } from '../../../config/env.js';
import { FileStorage } from './file-storage.js';

/** Absolute path of UPLOADS_DIR (relative paths resolve from the working directory). */
export function uploadsRoot(config: ConfigService<Env, true>): string {
  return resolve(config.get('UPLOADS_DIR', { infer: true }));
}

/** Files on the local disk under UPLOADS_DIR, served by setupApp at /uploads. */
@Injectable()
export class LocalFileStorage extends FileStorage {
  private readonly root: string;
  private readonly publicUrl: string;

  constructor(config: ConfigService<Env, true>) {
    super();
    this.root = uploadsRoot(config);
    this.publicUrl = config.get('PUBLIC_UPLOADS_URL', { infer: true });
  }

  async save(key: string, data: Buffer): Promise<string> {
    const path = resolve(this.root, key);
    // Keys are generated by the API, but never write outside the root anyway.
    const inside = relative(this.root, path);
    if (inside === '' || inside.startsWith('..') || isAbsolute(inside)) {
      throw new Error(`Invalid storage key: ${key}`);
    }
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, data, { flag: 'wx' });
    return `${this.publicUrl}/${inside.split(sep).join('/')}`;
  }
}
